#!/usr/bin/bash -e
# postinst script for allmon3
#
# see: dh_installdeb(1)

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#
set -e

if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
    . /usr/share/apache2/apache2-maintscript-helper
fi

do_configure() {

	#Apache Management
    if [ -e /usr/sbin/apache2 ]; then
        apache2_invoke enmod ssl || exit $?
        apache2_invoke ensite default-ssl || exit $?
		apache2_invoke enmod headers || exit $?
		apache2_invoke enconf nocache || exit $?
    fi

	# Services to start on boot
	deb-systemd-invoke enable apache2
	deb-systemd-invoke enable allmon3
	deb-systemd-invoke enable asterisk
	deb-systemd-invoke enable firewalld
	deb-systemd-invoke enable cockpit.socket

	# Change default firewalld zone
	if [ "$(firewall-cmd --state)" = "running" ]; then
		deb-systemd-invoke reload firewalld
		firewall-cmd --set-default-zone=allstarlink
		firewall-cmd --zone=allstarlink --permanent --add-service=echolink
		firewall-cmd --zone=allstarlink --add-service=echolink
	else
		set +e
		firewall-offline-cmd --set-default-zone=allstarlink
		firewall-offline-cmd --zone=allstarlink --add-service=echolink
	fi

	set -e

	# Setup avahi-daemon
	perl -pi -e 's/^publish-workstation=[A-Za-z]+\s?$/publish-workstation=yes\n/' /etc/avahi/avahi-daemon.conf
	perl -pi -e 's/^publish-hinfo=[A-Za-z]+\s?$/publish-hinfo=yes\n/' /etc/avahi/avahi-daemon.conf
	rm -f /etc/avahi/services/http.service /etc/avahi/services/https.service /etc/avahi/services/cockpit.service
	deb-systemd-invoke enable avahi-daemon
	deb-systemd-invoke restart avahi-daemon

	# Rewrite the motd
	cat - > /etc/motd <<EOF

            Welcome to AllStarLink v3

 * A CLI menu is accessible by typing 'sudo asl-menu'
 * The Asterisk CLI is accessible by typing 'sudo asterisk -rv'
 * An online manual is located at https://allstarlink.github.io
 * Package updates are obtained through the Cockpit web
   console or by typing 'sudo apt update && sudo apt upgrade -y'
 * This system uses firewalld. Ports are controlled in the
   Cockpit web console or by using the command:
     'sudo firewall-cmd -p PORT:TYPE'
 * For help, visit https://community.allstarlink.org

EOF

	# Customize /etc/os-release
	/usr/share/cockpit/branding/debian-AllStarLink/fix-os-release

	# Customize dphys-swapfile if its installed
	if [ -f /etc/dphys-swapfile ]; then
		# Undo the previous swap manipulations
		perl -pi -e 's/^CONF_SWAPSIZE/##CONF_SWAPSIZE/g' /etc/dphys-swapfile

		# Increase the swapfile default sizes on systems with < 512M
		RAMK=$(getconf -a | grep PAGES | awk 'BEGIN {total = 1} {if (NR == 1 || NR == 3) total *=$NF} END {print total / 1024}')
		if [[ $RAMK -lt 512000 ]]; then
			if ! grep -q -E '^CONF_SWAPFACTOR' /etc/dphys-swapfile; then
				echo "CONF_SWAPFACTOR=4" >> /etc/dphys-swapfile
				echo "NOTICE: changed /etc/dphys-swapfile; reboot required!"
			fi
		fi
		deb-systemd-invoke enable dphys-swapfile
	
	fi

	# Enable the Pi UART as /dev/serial0 if this looks like a Pi
	PLATFORM=$(grep -E '^Model' /proc/cpuinfo | awk '{print $3$4}')
	if [ "${PLATFORM}" == "RaspberryPi" ]; then
		/usr/bin/asl-enable-pi-serial
	fi

	# Cleanup /etc/rc.local from 3.0.15
	if [ -f /etc/rc.local ]; then

		# does this have the broken POSTROUTING iptables statement? If so, delete.
		if `grep -q POSTROUTING /etc/rc.local > /dev/null 2>&1`; then
			echo "Deleting corrupted /etc/rc.local from ASL3 image 3.0.15"
			rm -f /etc/rc.local
		fi

		# does this have the one-liner created by asl3-pi-appliance? If so, delete.
		if [ $(wc -l /etc/rc.local | awk '{print $1}') -eq 1 ]; then
			echo "Deleting corrupted /etc/rc.local from asl3-pi-appliance 1.9.0"
			rm -f /etc/rc.local
		fi
	fi

	if [ -f /etc/rc.local ]; then
		echo "WARNING!! /etc/rc.local found!"
		echo "Please read https://community.allstarlink.org/t/22604 carefully!"
	fi

	[ -f /boot/firmware/wifi.nmconnection ] && rm -f /boot/firmware/wifi.nmconnection
	[ -f /boot/wifi.nmconnection ] && rm -f /boot/wifi.nmconnection
	[ -f /etc/NetworkManager/system-connections/wifi.nmconnection ] && \
		rm -f /etc/NetworkManager/system-connections/wifi.nmconnection

	if [ -f /opt/custompios/copy-network-manager-config ]; then
		rm -f /opt/custompios/copy-network-manager-config
	fi

	if [ -f /etc/systemd/system/copy-network-manager-config\@.service ]; then
		deb-systemd-invoke stop copy-network-manager-config@wlan0.service
		deb-systemd-invoke disable copy-network-manager-config@wlan0.service
		rm -f /etc/systemd/system/copy-network-manager-config\@.service
	fi

	# Cleanup broken cruft from CustomPiOS - https://github.com/AllStarLink/asl3-pi-appliance/issues/22
	perl -pi -e 's/^IPQoS\s+0x00$//' /etc/ssh/sshd_config
	deb-systemd-invoke restart ssh
}

case "$1" in
    configure)
		do_configure
    ;;
		triggered)
		/usr/share/cockpit/branding/debian-AllStarLink/fix-os-release
	;;
	    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0

